services:
  backend:
    hostname: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file: ./.env
    expose:
      - $PORT
  nginx:
    hostname: nginx
    image: nginx:stable-alpine-slim
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - backend