services:
    backend:
        hostname: backend
        image: registry.miem.hse.ru/kg25-26/bkkarpuzov/backend:latest
        build:
            context: ./backend
            dockerfile: Dockerfile
        expose:
            - 5000
        environment:
            - HOST=0.0.0.0
            - API_LINK=http://api.localhost
    frontend:
        hostname: frontend
        image: registry.miem.hse.ru/kg25-26/bkkarpuzov/frontend:latest
        build:
            context: ./frontend
            dockerfile: Dockerfile
        expose:
            - 3000
    nginx:
        hostname: nginx
        image: nginx:stable-alpine-slim
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        ports:
            - "80:80"
        depends_on:
            - backend
            - frontend
